import enum 
class USER_ERROR_CODES(enum.Enum):
    EMPTY_INPUT = "EMPTY_INPUT"
    UNSUPPORTED_INPUT = "UNSUPPORTED_INPUT"
    PROMPT_INJECTION_DETECTED = "PROMPT_INJECTION_DETECTED"
    INAPPROPRIATE_CONTENT = "INAPPROPRIATE_CONTENT"
    UNKNOWN_INPUT = "UNKNOWN_INPUT"
    
    
    #auth:
    UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    
    #service:
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"

    #duplicate
    INPUT_ALREADY_EXISTS = "INPUT_ALREADY_EXISTS"

class SYSTEM_ERROR_CODES(enum.Enum):
    #Ai related:
    MY_QUOTA_REACHED = "MY_QUOTA_REACHED"
    AI_SERVICE_FAILURE = "AI_SERVICE_FAILURE"
    AI_REPAIR_FAILURE = "AI_REPAIR_FAILURE" 
    RAW_REPAIR_FAILURE = "RAW_REPAIR_FAILURE"

    #App realted:
    
    
    
    #DB related:
    DATABASE_ERROR = "DATABASE_ERROR"
    
    
    #system:
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
    
    
    #redis:
    
    
    
    #redis-session-sets:
    NO_AVALIBLE_SESSIONS = "NO_AVALIBLE_SESSIONS"
    
    
    #celery workers:
    WORKER_PROCESS_FAILED = "WORKER_PROCESSED_FAILED"
    WORKER_PROCESS_RETRYING = "WORKER_PROCESSED_RETRYING"
    WORKER_IN_PROCESS = "WORKER_IN_PROCESS"